apiVersion: v1
kind: Secret

metadata:
  name: java-app-secret

type: Opaque    # generic secret (other types: kubernetes.io/tls, kubernetes.io/dockerconfigjson)

# Values MUST be base64 encoded
# Encode: [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("supersecret"))
# Decode: [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("c3VwZXJzZWNyZXQ="))
data:
  DB_PASSWORD: c3VwZXJzZWNyZXQ=     # "supersecret"
  REDIS_PASSWORD: ""                  # empty (Redis has no password in dev)
