spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=<--username-->
spring.datasource.password=<--username-->

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0

aws.access.key=<-- AWS KEY -->
aws.secret.key=<-- AWS SECRET KEY -->
aws.region=<-- AWS SECRET REGION -->
aws.bucket.name=<-- AWS BUCKET NAME -->

jwt.secret.key=thisismysecretkeyfortheUpcomingproject

razorpay.key.id=<-- Razorpay Key -->
razorpay.key.secret=<-- Razorpay Secret -->

