apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: javaapp
type: Opaque
data:
  # "supersecret" → base64
  DB_PASSWORD: c3VwZXJzZWNyZXQ=
  # "appuser" → base64
  POSTGRES_USER: YXBwdXNlcg==
  # "supersecret" → base64
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXQ=
